# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92ba38651312740f4afb59060dc9ce7dc79cccabc77dfff6eb70401381cfbb2f65904941a0e03e6696233c037226b456a001c208110d78e49418779378342527

test:
  secret_key_base: e44414712e324d875adf75ee4a4a4c660bac3f1ff6e529ccb5046a4d0207c3cb39f9c1f27b572c11a73c43367f09907766274f642e76350cb51b579ec355e14a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
